(LAMBDA (XS YS) (COND ((NULL XS) (COND ((NULL YS) NIL) (T (ERROR YS (QUOTE REDUNDANT))))) ((NULL YS) (COND ((NULL XS) NIL) (T (ERROR YS (QUOTE MISSING))))) (T (CONS (SET (CAR XS) (CAR YS)) (BIND (CDR XS) (CDR YS))))))
(C D)
C
D
