(LAMBDA (X XS) (COND ((NULL XS) (CONS X NIL)) (T (CONS (CAR XS) (APPEND X (CDR XS))))))
(A B C)
Error: ((LAMBDA (X XS) (COND ((NULL XS) (CONS X NIL)) (T (CONS (CAR XS) (APPEND X (CDR XS)))))) (QUOTE A)) - MISSING
?
