#undef  action                             
#undef  Alias                              
#undef  Allocate                           
#undef  array                              
#undef  As                                 
#undef  below           ;                  
#undef  by                                 
#undef  Capsule                            
#undef  CONCATENATE1                       
#undef  CONCATENATE2                       
#undef  CONCATENATE                        
#undef  constant                           
#undef  CONTEXT                            
#undef  COUNT1                             
#undef  COUNT                              
#undef  doing                              
#undef  Done                               
#undef  do                                 
#undef  ELABORATE                          
#undef  expect                             
#undef  expecting                          
#undef  __EXPRESSION                       
#undef  fail                               
#undef  _fe0                               
#undef  _fe1                               
#undef  _fe2                               
#undef  _fe3                               
#undef  _fe4                               
#undef  _fe5                               
#undef  _fe6                               
#undef  _fe7                               
#undef  _fe8                               
#undef  _fe9                               
#undef  Feature                            
#undef  feature                            
#undef  Filling                            
#undef  Fill                               
#undef  Fluenter                           
#undef  Fluent                             
#undef  from                               
#undef  FUN                                
#undef  GET_MACRO                          
#undef  Hides           
#undef  Hiding          
#undef  Implementation  
#undef  is              
#undef  IS              
#undef  let             
#undef  Let             
#undef  maintain        
#undef  maintaining     
#undef  Make            
#undef  MAP                                
#undef  modifier                           
#undef  Module         
#undef  Mutator                            
#undef  nothing                            
#undef  Occasionally                       
#undef  pairing                            
#undef  Perform                            
#undef  perhap                             
#undef  Perspective                        
#undef  PREDICATE     
#undef  procedure     
#undef  promise       
#undef  promising     
#undef  Property      
#undef  Provides      
#undef  Query         
#undef  query         
#undef  Representation
#undef  Return        
#undef  Selfer        
#undef  selfing       
#undef  Service       
#undef  taking                             
#undef  then            ,                  
#undef  TO_STRING1                         
#undef  TO_STRING2                         
#undef  TO_STRING                          
#undef  Typed                              
#undef  Type                  
#undef  unique                
#undef  Unit                  
#undef  VA_ARGS               
#undef  variable              
#undef  variable              
#undef  with                  
#undef  X1                    
#undef  X2                    
#undef  X3                    
#undef  X4                    
#undef  X5                    
